### PR TITLE
fix: timepicker now is displayed with correct value

### LINKED ISSUE #791: Datetime picker filter loading doesn't work
When we apply a datetime filter to tasks, the applied filter doesn't show up when we click on manage filters

### PR DESCRIPTION
**Pull request by Faust1-2was-Aneo**
close #791

### CODE REVIEW

File: src/app/components/filters/filters-chips.component.ts [hunk 1]
```diff
@@ -72,7 +71,7 @@ export class FiltersChipsComponent<T extends number, U extends number | null = n
       return `${label} ${operator} ${status?.value}`;
     }
     else if (type === 'date') {
-      return `${label} ${operator} ${DateTime.fromSeconds(Number(filter.value)).toISODate()}`;
+      return `${label} ${operator} ${new Date(Number(filter.value) * 1000).toLocaleString()}`;
```
Comment (ngruelaneo) [inline src/app/components/filters/filters-chips.component.ts:74]: les dates doivent etre en UTC

**Review by ngruelaneo — APPROVED** [review]
